from fastapi import APIRouter, Request, BackgroundTasks
import hashlib
import hmac
from app.core.config import settings
from app.services.github_service import github_service
from app.agents.review_monk import ReviewMonkAgent
import logging

router = APIRouter()
logger = logging.getLogger(__name__)
review_monk = ReviewMonkAgent()

async def process_pr_review(repo_full_name: str, pr_number: int, pr_title: str):
    """Background task to review code and post comments"""
    logger.info(f"Starting review for {repo_full_name}#{pr_number}")
    
    # 1. Fetch Diff
    diff = await github_service.get_pr_diff(repo_full_name, pr_number)
    
    if not diff:
        logger.error("Could not fetch diff. Aborting.")
        return

    # 2. Run AI Analysis
    review_result = await review_monk.process(
        {"diff": diff, "pr_title": pr_title},
        session_id=f"gh-{repo_full_name}-{pr_number}"
    )
    
    # 3. Format Comment
    if "error" in review_result:
        body = f"⚠️ **Review Monk Error**: {review_result['error']}"
    else:
        # Construct markdown from JSON
        summary = review_result.get("summary", "No summary.")
        flaws = review_result.get("findings", [])
        score = review_result.get("quality_score", "?")
        
        body = f"## 🐵 Review Monk Analysis\n\n"
        body += f"**Quality Score**: {score}/10\n\n"
        body += f"### Summary\n{summary}\n\n"
        
        if flaws:
            body += "### 🚨 Key Findings\n"
            for flaw in flaws:
                icon = "🔴" if flaw['severity'] == "CRITICAL" else "🟠" if flaw['severity'] == "HIGH" else "🔵"
                body += f"- {icon} **{flaw['severity']}**: {flaw['issue']} (File: `{flaw['file']}`)\n"
                body += f"  > Suggestion: {flaw['suggestion']}\n\n"
        
        body += "\n---\n*Generated by CodeSherpa AI 🇮🇳*"

    # 4. Post back to GitHub
    await github_service.post_comment(repo_full_name, pr_number, body)
    logger.info(f"Posted review for {repo_full_name}#{pr_number}")


@router.post("/webhook")
async def github_webhook(request: Request, background_tasks: BackgroundTasks):
    """endpoint to receive GitHub hooks"""
    # Verify Signature (skipped for hackathon speed if secret missing, but good practice)
    payload = await request.json()
    
    event = request.headers.get("X-GitHub-Event")
    
    if event == "pull_request":
        action = payload.get("action")
        if action in ["opened", "synchronize", "reopened"]:
            pr = payload.get("pull_request")
            repo = payload.get("repository")
            
            # Start background processing (don't block webhook)
            background_tasks.add_task(
                process_pr_review,
                repo_full_name=repo["full_name"],
                pr_number=pr["number"],
                pr_title=pr["title"]
            )
            
    return {"status": "accepted"}
